# Generated by Django 5.1.3 on 2024-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vete', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
