# Generated by Django 5.1.3 on 2024-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vete', '0004_mascota_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='historial',
            field=models.TextField(null=True),
        ),
    ]
